// Rasterize the authored indexed art once. An image keeps a creature intact at
// small sizes; hundreds of fractional View strips do not share pixel edges.
import { mkdirSync, writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { SPRITES, SPRITE_PALETTES } from '../src/data/sprites.js';
import { idleFrame } from '../src/data/idleFrame.js';
const alphabet = '!#$%&()*+,-/0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{|}~';
const dir = new URL('../assets/creature-bitmaps/', import.meta.url);
mkdirSync(dir, { recursive: true });
function crc(buf) {
  let n = 0xffffffff;
  for (const byte of buf) {
    n ^= byte;
    for (let i = 0; i < 8; i++) n = (n >>> 1) ^ ((n & 1) ? 0xedb88320 : 0);
  }
  return (n ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const name = Buffer.from(type);
  const length = Buffer.alloc(4); length.writeUInt32BE(data.length);
  const checksum = Buffer.alloc(4); checksum.writeUInt32BE(crc(Buffer.concat([name, data])));
  return Buffer.concat([length, name, data, checksum]);
}
let table = '// Generated by tools/render_sprite_bitmaps.mjs. Two authored idle frames per sheet.\nexport const CREATURE_BITMAPS = {\n';
let count = 0;
for (const [key, sprite] of Object.entries(SPRITES)) {
  if (!sprite.palette.startsWith('art_')) continue;
  const w = sprite.grid[0].length;
  const rows = [...sprite.grid, ...idleFrame(key, sprite.grid, w)];
  const h = rows.length;
  const data = Buffer.alloc(h * (w * 4 + 1));
  const palette = SPRITE_PALETTES[sprite.palette];
  rows.forEach((row, y) => [...row].forEach((ch, x) => {
    if (ch === '.') return;
    const hex = palette[alphabet.indexOf(ch)];
    if (!hex || hex === 'transparent') return;
    const offset = y * (w * 4 + 1) + 1 + x * 4;
    data[offset] = parseInt(hex.slice(1, 3), 16);
    data[offset + 1] = parseInt(hex.slice(3, 5), 16);
    data[offset + 2] = parseInt(hex.slice(5, 7), 16);
    data[offset + 3] = 255;
  }));
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(w); ihdr.writeUInt32BE(h, 4); ihdr[8] = 8; ihdr[9] = 6;
  const png = Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]), chunk('IHDR', ihdr), chunk('IDAT', deflateSync(data)), chunk('IEND', Buffer.alloc(0))]);
  writeFileSync(new URL(`${key}.png`, dir), png);
  table += `  '${key}': { source: require('../../assets/creature-bitmaps/${key}.png'), aspect: ${sprite.grid.length / w} },\n`;
  count++;
}
writeFileSync(new URL('../src/data/creatureBitmaps.js', import.meta.url), table + '};\n');
console.log(`Rasterized ${count} authored sprites with two idle frames each.`);
